name: blog-generator

dependencies:
  - base == 4.*
library:
  source-dirs: src
  ghc-options: -Wall -Werror

executables:
  blog-generator-exe:
    main: Main.hs
    ghc-options: -threaded -rtsopts -W -Wall -Werror
    dependencies:
    - blog-generator
